FROM debian:9
RUN apt-get update \
  && apt-get install -y openjdk-8-jdk cmake curl wget git unzip python

ARG ANDROID_COMPILE_SDK=29
ARG ANDROID_BUILD_TOOLS=
ARG ANDROID_SDK_TOOLS=4333796 
ARG ANDROID_NDK_TOOLS=21.1.6352462

RUN wget --quiet --output-document=/tmp/sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_TOOLS.zip \
    && unzip /tmp/sdk-tools-linux.zip -d $HOME/.android \
    && mkdir -p $HOME/.android \ 
    && touch $HOME/.android/repositories.cfg \
    && mkdir $HOME/.android/licenses \
    && echo y | $HOME/.android/tools/bin/sdkmanager "ndk;$ANDROID_NDK_TOOLS" >/dev/null \
    && echo y | $HOME/.android/tools/bin/sdkmanager "platform-tools" "platforms;android-$ANDROID_COMPILE_SDK" >/dev/null \
    && echo y | $HOME/.android/tools/bin/sdkmanager "system-images;android-$ANDROID_COMPILE_SDK;default;x86" >/dev/null 


RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && . $HOME/.cargo/env \
    && rustup target add armv7-linux-androideabi \
    && rustup target add aarch64-linux-android \
    && rustup target add i686-linux-android

ENV ANDROID_HOME=/root/.android
ENV ANDROID_SDK_ROOT=/root/.android
ENV PATH=~/.cargo/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.android/platform-tools
